name: InteractivePartners
favicon: null
layout_spectrum: 0.3370605637319386
typography_spectrum: 0.171029087388888
title: Interactive Partners  - Web and Application Developers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#67a6c7'
    - '#bcdb4a'
    - '#2c8bae'
    - '#85cdf2'
    - '#fbfcfb'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
